springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  packages-to-scan: com.eodi.yak.eodi_yak.domain

server:
  port: 8080

spring:
  mvc:
    messages:
      encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: 'jdbc:h2:file:./db/eodi-yak'  # 파일 기반 H2 데이터베이스

    #url: 'jdbc:h2:mem:test;MODE=MYSQL'   # H2 DB 연결 주소 (In-Memory Mode)
    #url: 'jdbc:h2:tcp://localhost/~/eodi-yak'
    driver-class-name: org.h2.Driver
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always